services:
  internal_module:
    container_name: internal_module
    build:
      context: .
      dockerfile: ./internal_module/Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - /mnt/allshare_fileserver/barometer_vacancies:/mnt/allshare_fileserver/barometer_vacancies
    restart: unless-stopped
